site_name: Kuadrant Documentation
site_url: https://docs.kuadrant.io/
repo_url: https://github.com/kuadrant/docs.kuadrant.io
edit_uri: edit/main/docs/
extra:
  version:
    provider: mike
    default:
      - latest
theme:
  name: material
  logo: assets/images/logo.png
  custom_dir: overrides
  features:
    - content.action.edit
    - content.code.copy
extra_css:
  - assets/stylesheets/extra.css
watch:
  - overrides
markdown_extensions:
  - mdx_breakless_lists
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - footnotes
  - admonition
  - pymdownx.details
  - toc:
      permalink: true
plugins:
  - mike:
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ''
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js
  - search
  - multirepo:
      cleanup: true
      keep_docs_dir: true
      nav_repos:
        - name: kuadrant-operator
          import_url: 'https://github.com/kuadrant/kuadrant-operator?edit_uri=/blob/main/&branch=main'
          imports:
            - /README.md
            - /doc/*
            - /config/samples/*
            - /examples/*
        - name: authorino
          import_url: 'https://github.com/kuadrant/authorino?edit_uri=/blob/main/&branch=main'
          imports:
            - /README.md
            - /docs/*
            - /docs/user-guides/*
            - /install/crd/*
        - name: authorino-operator
          import_url: 'https://github.com/kuadrant/authorino-operator?edit_uri=/blob/main/&branch=main'
          imports:
            - /README.md
        - name: limitador
          import_url: 'https://github.com/kuadrant/limitador?edit_uri=/blob/main/&branch=main'
          imports:
            - /README.md
            - /doc/*
            - /limitador-server/README.md
            - /limitador-server/docs/*
            - /limitador/README.md
            - /limitador-server/kubernetes/*
            - /limitador-server/sandbox/*
            - /LICENSE
        - name: limitador-operator
          import_url: 'https://github.com/kuadrant/limitador-operator?edit_uri=/blob/main/&branch=main'
          imports:
            - /README.md
            - /doc/*
        - name: architecture
          import_url: 'https://github.com/kuadrant/architecture?edit_uri=/blob/main/&branch=main'
          imports:
            - /docs/design/*
        - name: kuadrantctl
          import_url: 'https://github.com/kuadrant/kuadrantctl?edit_uri=/blob/main/&branch=main'
          imports:
            - /README.md
            - /doc/*
        - name: dns-operator
          import_url: 'https://github.com/kuadrant/dns-operator?edit_uri=/blob/main/&branch=main'
          imports:
            - /README.md
            - /docs/*
            - /config/samples/*
  - redirects:
      redirect_maps:
        'getting-started-single-cluster.md': 'getting-started.md'
        'getting-started-multi-cluster.md': 'getting-started.md'
        'kuadrant-operator/doc/install/install-kubernetes.md': 'getting-started.md'
        'kuadrant-operator/doc/install/install-openshift.md': 'getting-started.md'
        'kuadrant-operator/doc/user-guides/full-walkthrough/secure-protect-connect-k8s.md': 'kuadrant-operator/doc/user-guides/full-walkthrough/secure-protect-connect.md'
        'kuadrant-operator/doc/user-guides/full-walkthrough/secure-protect-connect-openshift.md': 'kuadrant-operator/doc/user-guides/full-walkthrough/secure-protect-connect.md'
nav:
  - 'Overview': index.md
  - 'Getting Started': getting-started.md
  - 'Installation':
      - 'Install with Helm': install-helm.md
      - 'Install with OLM': install-olm.md
  - 'Concepts':
      - 'Architecture': architecture/docs/design/architectural-overview-v1.md
      - 'DNSPolicy': kuadrant-operator/doc/overviews/dns.md
      - 'TLSPolicy': kuadrant-operator/doc/overviews/tls.md
      - 'AuthPolicy': kuadrant-operator/doc/overviews/auth.md
      - 'RateLimitPolicy': kuadrant-operator/doc/overviews/rate-limiting.md
  - 'APIs & Reference':
      - 'DNSPolicy': kuadrant-operator/doc/reference/dnspolicy.md
      - 'TLSPolicy': kuadrant-operator/doc/reference/tlspolicy.md
      - 'AuthPolicy': kuadrant-operator/doc/reference/authpolicy.md
      - 'RateLimitPolicy': kuadrant-operator/doc/reference/ratelimitpolicy.md   
      - 'Kuadrant': kuadrant-operator/doc/reference/kuadrant.md         
      - 'Observability':
          - 'Metrics': kuadrant-operator/doc/observability/metrics.md
          - 'Authentication and Authorization': authorino/docs/user-guides/observability.md
  - 'Tutorials':
      - 'Secure, connect and protect': kuadrant-operator/doc/user-guides/full-walkthrough/secure-protect-connect.md
      - 'Gateway TLS for Cluster Operators': kuadrant-operator/doc/user-guides/tls/gateway-tls.md
      - 'Enforcing authentication & authorization with Kuadrant AuthPolicy': kuadrant-operator/doc/user-guides/auth/auth-for-app-devs-and-platform-engineers.md
      - 'Gateway Rate Limiting for Cluster Operators': kuadrant-operator/doc/user-guides/ratelimiting/gateway-rl-for-cluster-operators.md
      - 'Authenticated Rate Limiting for Application Developers': kuadrant-operator/doc/user-guides/ratelimiting/authenticated-rl-for-app-developers.md
      - 'Authenticated Rate Limiting with JWTs and Kubernetes RBAC': kuadrant-operator/doc/user-guides/ratelimiting/authenticated-rl-with-jwt-and-k8s-authnz.md
      - 'Gateway Rate Limiting': kuadrant-operator/doc/user-guides/ratelimiting/multi-auth-rlp-diff-section.md
      - 'Multi authenticated Rate Limiting for an Application': kuadrant-operator/doc/user-guides/ratelimiting/multi-auth-rlp-same-section.md
  - 'Guides':
      - 'DNS configuration':
          - 'Configuring a DNS Provider': dns-operator/docs/provider.md
          - 'Gateway DNS for ingress Gateway': kuadrant-operator/doc/user-guides/dns/gateway-dns.md
          - 'Basic DNS': kuadrant-operator/doc/user-guides/dns/basic-dns-configuration.md
          - 'DNS Load Balancing': kuadrant-operator/doc/user-guides/dns/load-balanced-dns.md
          - 'Health Checks': kuadrant-operator/doc/user-guides/dns/dnshealthchecks.md
      - 'mTLS Configuration': kuadrant-operator/doc/install/mtls-configuration.md
      - 'Observability':
          - 'Dashboards and Alerts': kuadrant-operator/doc/observability/examples.md
          - 'Tracing': kuadrant-operator/doc/observability/tracing.md
