site_name: Kuadrant Documentation
site_url: https://docs.kuadrant.io/
repo_url: https://github.com/kuadrant/docs.kuadrant.io
edit_uri: edit/main/docs/
extra:
  version:
    provider: mike
    default:
      - 0.11.0
      - latest
theme:
  name: material
  logo: assets/images/logo.png
  custom_dir: overrides
  features:
    - content.action.edit
    - content.code.copy
extra_css:
  - assets/stylesheets/extra.css
watch:
  - overrides
markdown_extensions:
  - mdx_breakless_lists
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - footnotes
  - admonition
  - pymdownx.details
  - toc:
      permalink: true
plugins:
  - mike:
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ''
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js
  - search
  - multirepo:
      cleanup: true
      keep_docs_dir: true
      nav_repos:
        - name: kuadrant-operator
          import_url: 'https://github.com/kuadrant/kuadrant-operator?edit_uri=/blob/main/&branch=main'
          imports:
            - /README.md
            - /doc/*
            - /config/samples/*
            - /examples/*
        - name: authorino
          import_url: 'https://github.com/kuadrant/authorino?edit_uri=/blob/main/&branch=main'
          imports:
            - /README.md
            - /docs/*
            - /docs/user-guides/*
            - /install/crd/*
        - name: authorino-operator
          import_url: 'https://github.com/kuadrant/authorino-operator?edit_uri=/blob/main/&branch=main'
          imports:
            - /README.md
        - name: limitador
          import_url: 'https://github.com/kuadrant/limitador?edit_uri=/blob/main/&branch=main'
          imports:
            - /README.md
            - /doc/*
            - /limitador-server/README.md
            - /limitador-server/docs/*
            - /limitador/README.md
            - /limitador-server/kubernetes/*
            - /limitador-server/sandbox/*
            - /LICENSE
        - name: limitador-operator
          import_url: 'https://github.com/kuadrant/limitador-operator?edit_uri=/blob/main/&branch=main'
          imports:
            - /README.md
            - /doc/*
        - name: architecture
          import_url: 'https://github.com/kuadrant/architecture?edit_uri=/blob/main/&branch=main'
          imports:
            - /rfcs/*
            - /docs/*
        - name: kuadrantctl
          import_url: 'https://github.com/kuadrant/kuadrantctl?edit_uri=/blob/main/&branch=main'
          imports:
            - /README.md
            - /doc/*
        - name: dns-operator
          import_url: 'https://github.com/kuadrant/dns-operator?edit_uri=/blob/main/&branch=main'
          imports:
            - /README.md
            - /docs/*
            - /config/samples/*
nav:
  - 'Overview': index.md
  - 'Getting Started':
      - 'Single-Cluster': getting-started-single-cluster.md
      - 'Multi-Cluster': getting-started-multi-cluster.md
  - 'Architecture': architecture/docs/design/architectural-overview-v1.md
  - 'Installation':
      - 'Kubernetes': kuadrant-operator/doc/install/install-kubernetes.md
      - 'OpenShift': kuadrant-operator/doc/install/install-openshift.md
  - 'Concepts and APIs':
      - 'DNSPolicy':
          - 'Overview': kuadrant-operator/doc/overviews/dns.md
          - 'Reference': kuadrant-operator/doc/reference/dnspolicy.md
      - 'TLSPolicy':
          - 'Overview': kuadrant-operator/doc/overviews/tls.md
          - 'Reference': kuadrant-operator/doc/reference/tlspolicy.md
      - 'AuthPolicy':
          - 'Overview': kuadrant-operator/doc/overviews/auth.md
          - 'Reference': kuadrant-operator/doc/reference/authpolicy.md
      - 'RateLimitPolicy':
          - 'Overview': kuadrant-operator/doc/overviews/rate-limiting.md
          - 'Reference': kuadrant-operator/doc/reference/ratelimitpolicy.md
  - 'How-to Guides':
      - 'Secure, connect and protect': kuadrant-operator/doc/user-guides/full-walkthrough/secure-protect-connect.md
      - 'DNS configuration':
          - 'Configuring a DNS Provider': dns-operator/docs/provider.md
          - 'Gateway DNS for ingress Gateway': kuadrant-operator/doc/user-guides/dns/gateway-dns.md
          - 'Basic DNS': kuadrant-operator/doc/user-guides/dns/basic-dns-configuration.md
          - 'DNS Load Balancing': kuadrant-operator/doc/user-guides/dns/load-balanced-dns.md
          - 'Health Checks': kuadrant-operator/doc/user-guides/dns/dnshealthchecks.md
      - 'TLS configuration':
          - 'Gateway TLS for Cluster Operators': kuadrant-operator/doc/user-guides/tls/gateway-tls.md
      - 'mTLS Configuration': kuadrant-operator/doc/install/mtls-configuration.md
      - 'Authentication & Authorization':
          - 'AuthPolicy for Application Developers and Platform Engineers': kuadrant-operator/doc/user-guides/auth/auth-for-app-devs-and-platform-engineers.md
      - 'Rate Limiting':
          - 'RateLimitPolicy for Platform Engineers': kuadrant-operator/doc/user-guides/ratelimiting/gateway-rl-for-cluster-operators.md
          - 'Authenticated Rate Limiting for Application Developers': kuadrant-operator/doc/user-guides/ratelimiting/authenticated-rl-for-app-developers.md
          - 'Authenticated Rate Limiting with JWTs and Kubernetes RBAC': kuadrant-operator/doc/user-guides/ratelimiting/authenticated-rl-with-jwt-and-k8s-authnz.md
          - 'Authenticated Rate Limit Policies for different listeners in an ingress gateway': kuadrant-operator/doc/user-guides/ratelimiting/multi-auth-rlp-diff-section.md
          - 'Authenticated Rate Limit Policies for the same HTTPRoute rule': kuadrant-operator/doc/user-guides/ratelimiting/multi-auth-rlp-same-section.md
      - 'Observability':
          - 'Metrics': kuadrant-operator/doc/observability/metrics.md
          - 'Dashboards and Alerts': kuadrant-operator/doc/observability/examples.md
          - 'Tracing': kuadrant-operator/doc/observability/tracing.md
          - 'Authentication and Authorization': authorino/docs/user-guides/observability.md
  - 'Proposals':
      - 'Request For Comments (RFC)':
          - 'RFC 0001: RateLimitPolicy API "v2"': architecture/rfcs/0001-rlp-v2.md
          - 'RFC 0002: Well-known Attributes': architecture/rfcs/0002-well-known-attributes.md
          - 'RFC 0003: DNSPolicy': architecture/rfcs/0003-dns-policy.md
          - 'RFC 0004: Policy Status': architecture/rfcs/0004-policy-status.md
          - 'RFC 0005: Single Cluster DNSPolicy': architecture/rfcs/0005-single-cluster-dnspolicy.md
          - 'RFC 0006: Configuration of Kuadrant Sub Components': architecture/rfcs/0006-kuadrant_sub_components_configurations.md
          - 'RFC 0007: Policy Sync': architecture/rfcs/0007-policy-sync-v1.md
          - 'RFC 0008: Kuadrant Release Process': architecture/rfcs/0008-kuadrant-release-process.md
          - 'RFC 0009: Defaults & Overrides': architecture/rfcs/0009-defaults-and-overrides.md
          - 'RFC 0010: Gateway API Metrics Exporter': architecture/rfcs/0010-gateway-api-metrics-exporter.md
          - 'RFC 0011: Policy Machinery for reconciliation': architecture/rfcs/0011-policy-machinery.md