name: Broken Links Check
on:
  workflow_dispatch:
env:
  WEBSITE_URL: "https://docs.kuadrant.io/"
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Run Broken Links Checker
      run: npx broken-link-checker $WEBSITE_URL --ordered --recursive --exclude-external
