name: Mike Deployment Trigger

on:
  issue_comment:
    types: [created]

jobs:
  handle_comment:
    runs-on: ubuntu-latest
    if: github.event_name == 'issue_comment' && (startsWith(github.event.comment.body, '/mike deploy') || startsWith(github.event.comment.body, '/mike help'))
    steps:
      - name: Validate User and Setup for Deploy
        if: startsWith(github.event.comment.body, '/mike deploy')
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        if: startsWith(github.event.comment.body, '/mike deploy')
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
        if: startsWith(github.event.comment.body, '/mike deploy')
      - run: |
          if [[ "$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/collaborators/${{ github.actor }}/permission")" \
            =~ (\"permission\": \"admin\") ]]; then
            echo "User is authorized to deploy."
            echo "::set-output name=can_deploy::true"
          else
            echo "::error::User is not authorized to deploy."
            echo "::set-output name=can_deploy::false"
          fi
        id: validate_user
        if: startsWith(github.event.comment.body, '/mike deploy')
      - run: |
          git config --global user.name "Docs Deploy"
          git config --global user.email "kuadrant@googlegroups.com"
        if: steps.validate_user.outputs.can_deploy == 'true'
      - run: |
          VERSION=$(echo "${{ github.event.comment.body }}" | cut -d " " -f 3)
          BRANCH=$(echo "${{ github.event.comment.body }}" | cut -d "=" -f 2)
          mike deploy $VERSION -t "$VERSION" --push --branch $BRANCH
        if: steps.validate_user.outputs.can_deploy == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Provide Help
        if: startsWith(github.event.comment.body, '/mike help')
        run: |
          echo "To deploy documentation using mike, use the command format:" > comment.md
          echo "/mike deploy [version] sourceBranch=[branch]" >> comment.md
          echo "Example: /mike deploy 0.7.0 sourceBranch=0.7.x" >> comment.md
          gh issue comment ${{ github.event.issue.number }} --body "$(cat comment.md)"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
